import type { Metadata } from "next";
import "./globals.css";
// Fonts
import { Fira_Code } from "next/font/google";
// Components
import NavBar from "./components/common/NavBar";
import PostList from "./components/posts/PostList";

// If loading a variable font, you don't need to specify the font weight
const inter = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "vsCode Like Blog",
  description: "vsCode Like Blog generated by jihokim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="relative" lang="en">
      <body
        className={`${inter.className} flex flex-row w-screen overflow-x-hidden relative`}
      >
        <NavBar />
        <PostList />
        {children}
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
